import type { ProgressSnapshot } from "../types.js";

export const SNAPSHOT_MARKER = "<!-- asteria-ai-worker:snapshot -->";

export function buildQuarantineComment(reason: string, mention: string): string {
  return `## ⚠️ Task Quarantined

**Reason:** ${reason}

${mention}, this task requires your attention before the agent can continue.

---
*Generated by asteria-ai-worker*`;
}

export function buildEvidenceComment(
  summary: string,
  filesChanged: string[],
  inputTokens: number,
  outputTokens: number
): string {
  const fileList =
    filesChanged.length > 0
      ? filesChanged.map((f) => `- \`${f}\``).join("\n")
      : "_No files modified_";

  return `## ✅ Task Completed

### Summary
${summary}

### Files Changed
${fileList}

### Token Usage
| Type | Count |
|------|-------|
| Input tokens | ${inputTokens.toLocaleString()} |
| Output tokens | ${outputTokens.toLocaleString()} |
| **Total** | **${(inputTokens + outputTokens).toLocaleString()}** |

---
*Generated by asteria-ai-worker*`;
}

export function buildErrorComment(error: string, stack?: string): string {
  const stackSection = stack
    ? `\n\n<details>\n<summary>Stack trace</summary>\n\n\`\`\`\n${stack}\n\`\`\`\n</details>`
    : "";

  return `## ❌ Agent Error

The agent encountered an unhandled error and could not complete the task.

**Error:** ${error}${stackSection}

---
*Generated by asteria-ai-worker*`;
}

export function buildPlanComment(plan: string): string {
  return `## 📋 Execution Plan

${plan}

---
*Generated by asteria-ai-worker*`;
}

export function buildProgressSnapshotComment(snapshot: ProgressSnapshot): string {
  return `## 💾 Progress Snapshot (Token Limit Reached)

The agent reached the token limit and saved a progress snapshot. It will resume from this point on the next run.

**Conversation summary:**
${snapshot.conversationSummary}

**Files changed so far:**
${snapshot.filesChanged.length > 0 ? snapshot.filesChanged.map((f) => `- \`${f}\``).join("\n") : "_None_"}

**Token usage:** ${(snapshot.totalInputTokens + snapshot.totalOutputTokens).toLocaleString()} total

${SNAPSHOT_MARKER}

\`\`\`json
${JSON.stringify(snapshot, null, 2)}
\`\`\`

---
*Generated by asteria-ai-worker*`;
}
